### ISSUE TITLE
Unable to access DNS zone in different Subscription?

### ISSUE THREAD

**Issue by davidheerema** [n3wt0n/AzureWebAppSSLManager#11]
Hello,

I have my DNS Zone in a different subscription from the AzureWebAppSSLManager and the App Services which it is servicing.  I think this is a problem.  The code is currently not able to reference a DNS Zone in another subscription, am I correct?

Dave.

**Comment by n3wt0n** [comment]
Yes, as stated in the README, in the Limitations section, you can manage resources in a single subscription.

PS: Sorry for the late reply, somehow I don't receive notifications for the new issues even if the notification system is on...
