### ISSUE TITLE
Allow using Staging Environment for Cert Generation

### ISSUE THREAD

**Issue by RichMercer** [n3wt0n/AzureWebAppSSLManager#13]
I am trying to figure out an issue with my App Service where a certificate is being created but cannot be installed. I pretty quickly hit the production rate limit, and there doesn't seem to be a way to allow using the staging environment to debug the issue.

**Comment by RichMercer** [comment]
On further inspection I see there is an Enum for CertificateMode but it would be great to have this available as a config option for when debugging or configuring the service.

**Comment by n3wt0n** [comment]
As you noticed, to use a Staging certificate, you need to change the value of “CertificateMode” to “Staging” in WebAppSSLManager.cs.

I agree with you that it’d be better having a setting for that without the need of redeploying. That will be add.

Thanks for reporting this.
