### ISSUE TITLE
Incorrect DNS entries created for national TLDs

### ISSUE THREAD

**Issue by thecontrarycat** [n3wt0n/AzureWebAppSSLManager#18]
**Issue**
It is currently impossible to create certificates for domains hosted by national registries (e.g. .co.uk) due to the way the DNS record is being created.

**Reproduction**
1. Try to create a certificate for `www.domain.co.uk`.  
2. Note that `AppProperty.BaseDomain == ".co.uk"` and therefore 
3. The DNS entry in the domain.co.uk root gets created as _acme-challenge.www.domain instead of _acme-challenge.www 

**Solution**
Use the name of the zone in Azure DNS as the BaseDomain as this is the way Azure DNS works.

**Comment by n3wt0n** [comment]
Good catch. I didn't think of that.
