### ISSUE TITLE
SSL for Slots

### ISSUE THREAD

**Issue by bbakermmc** [n3wt0n/AzureWebAppSSLManager#2]
Whats the app name when you want to deploy to a slot?
IE: 1 site with 3 slots.  www.site.com, dev.site.com, stage.site.com

**Comment by n3wt0n** [comment]
In App Service, Slots are basically separate apps.
As such, you could create different app definitions, one for each slot.

DISCLAIMER: I haven't had time to test this scenario yet, I will update this thread after the test

**Comment by n3wt0n** [comment]
As not said, I've seen that at API level the Deployment Slots are treated differently, so I need to differentiate it.

A possible solution would be to include a "IsSlot" param in the _appproperties.json_ file to be able to specify slots configuration. The result would be something like:
**Normal hostname**
```json
{
    "Hostname": "SUB.YOUR_DOMAIN.EXT",
    "AzureWebAppName": "ANOTHER_WEBAPP_RESOURCE_NAME",
    "AzureWebAppResGroup": "RESOURCE_GROUP_CONTAINING_THE_WEBAPP",
    "AzureDnsZoneName": "YOUR_DNS_RESOURCE_NAME",
    "AzureDnsResGroup": "RESOURCE_GROUP_CONTAINING_THE_DNS"
  }
```

**Slot hostname**
```json
{
    "Hostname": "SUB.YOUR_DOMAIN.EXT", 
    "AzureWebAppName": "ANOTHER_WEBAPP_RESOURCE_NAME",
    "AzureWebAppResGroup": "RESOURCE_GROUP_CONTAINING_THE_WEBAPP",
    "AzureDnsZoneName": "YOUR_DNS_RESOURCE_NAME",
    "AzureDnsResGroup": "RESOURCE_GROUP_CONTAINING_THE_DNS",
    "IsSlot": true,
    "SlotName": "YOUR_SLOT_NAME"
  }
```

Would this be acceptable?

**Comment by bbakermmc** [comment]
@n3wt0n Works for me but "IsSlot" is kind of redundant, if you have a "SlotName".

**Comment by n3wt0n** [comment]
@bbakermmc I agree it is kinda redundant, but I prefer making it explicit (so to avoid errors).
I would take the same approach for function apps (see #5)
