### ISSUE TITLE
New Cert variables hard coded

### ISSUE THREAD

**Issue by bbakermmc** [n3wt0n/AzureWebAppSSLManager#4]
Looking at the code, I assume these should be configured also?

https://github.com/n3wt0n/AzureWebAppSSLManager/blob/cfa7613a28c9ba1256ee55a3623a399cd55db07e/src/WebAppSSLManager/CertificatesHelper.cs#L125-L132

**Comment by n3wt0n** [comment]
Yes, you're right. I have to find the best way to set that data.
